# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='resources',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
